services:
  sokora:
    build: .
    container_name: sokora # rename to something else if you’re on canary
    restart: always
    volumes:
      - sokora_logs:/app/logs
      - ./.env:/app/.env
    env_file:
      - .env
    ports:
      - "3067:3067"
    develop:
      watch:
        - action: sync
          path: ./src
          target: ./app/src
          initial_sync: true
          ignore:
            - node_modules/
        - action: sync
          path: ./tests
          target: ./app/tests
          initial_sync: true
          ignore:
            - node_modules/
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: sokora
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: sokora-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sokora -d sokora-db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  sokora_logs:
